[package]
name = "rustycap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = { version = "1", features = ["capture-stream"] }
etherparse = "0.13"
libc = "0.2"
